name: example
description: Chatify example project
version: 1.0.3+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  chatify:
    path: ../
  firebase_core: ^2.24.2
  rxdart: ^0.27.7
  flutter_localizations:
    sdk: flutter
  lottie: ^2.7.0
  animated_typing: ^0.2.1
  get: ^4.6.6
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  fluttertoast: ^8.2.4
  kr_extensions: ^1.0.4
  flutter_shakemywidget: ^1.0.5+1
  kr_button: ^1.0.1
  stop_watch_timer: ^3.0.2
  motion_toast: ^2.7.10
  phone_number: ^2.0.1
  iconsax: ^0.0.8
  flutter_image_compress: ^1.1.3
  image_cropper: ^4.0.1
  otp_autofill: ^3.0.0
  vibration: ^1.8.4
  blur: ^3.1.0
  flutter_contacts: ^1.1.7+1
  collection: ^1.18.0
  permission_handler: ^11.1.0
  firebase_app_check: ^0.2.1+8
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/