name: example
description: Chatify example project
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  chatify:
    path: ../
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true