name: chatify
description: Chat package for flutter
version: 0.1.3
homepage: https://github.com/karrarfalih/chatify

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  any_link_preview: ^3.0.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  camera: ^0.10.5+5
  cloud_firestore: ^4.4.3
  connectivity_plus: ^5.0.1
  device_info_plus: ^9.1.0
  diffutil_dart: ^4.0.1
  emoji_picker_flutter: ^1.6.2
  firebase_database: ^10.2.6
  firebase_storage: ^11.0.14
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_bounce: ^1.1.0
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^1.1.3
  flutter_localizations:
   sdk: flutter
  flutter_sticky_header: ^0.6.5
  get: ^4.6.6
  http: ^0.13.6
  iconsax: ^0.0.8
  image_picker: ^1.0.6
  intl: ^0.18.0
  intl_translation: ^0.18.2
  just_audio: ^0.9.35
  lottie: ^2.6.0
  path_provider: ^2.0.13
  permission_handler: ^11.0.1
  photo_gallery: ^2.1.1
  provider: ^6.0.5
  record: ^4.4.4
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  swipeable_tile: ^2.0.0+3
  vibration: ^1.8.3
  zoom_widget: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/icons/
    - assets/lottie/

false_secrets:
 - example/ios/Runner/GoogleService-Info.plist
 - example/macos/Runner/GoogleService-Info.plist