name: chatify
description: Chat package for flutter
version: 0.1.1
homepage: https://github.com/karrarfalih/chatify

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cloud_firestore: ^4.4.3
  firebase_database: ^10.2.6
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  iconsax: any
  image_picker: ^0.8.6+4
  intl: ^0.18.1
  just_audio: ^0.9.31
  kr_paginate_firestore: ^1.0.4
  kr_pull_down_button: ^1.0.0
  optimized_cached_image: ^3.0.1
  path_provider: ^2.0.13
  record: ^4.4.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
