name: chatify
description: Chat package for flutter
version: 0.1.5
homepage: https://github.com/karrarfalih/chatify

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  camera: ^0.10.5+5
  cloud_firestore: ^4.4.3
  emoji_picker_flutter: ^1.6.2
  firebase_database: ^10.2.6
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^1.1.3
  iconsax: any
  image_picker: ^0.8.6+4
  intl: ^0.18.0
  just_audio: ^0.9.35
  kr_pull_down_button: ^1.0.0
  lottie: ^2.6.0
  optimized_cached_image: ^3.0.1
  path_provider: ^2.0.13
  permission_handler: ^11.0.1
  photo_gallery: ^2.1.1
  provider: ^6.0.5
  record: ^5.0.1
  shared_preferences: ^2.2.2
  vibration: ^1.8.3
  zoom_widget: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/lottie/
